---

- name: clone the oxy repo
  git:
    repo: "{{git_repo}}"
    version: "{{git_branch}}"
    dest: "{{oxy_base_dir}}"
    clone: yes
    update: no
  become: yes

- copy:
    src: "{{ role_path }}/files/sodium_fixer.sh"
    dest: /opt/oxy-node/

- name: Check if sodium_fixer has already been applied
  shell: grep 'npm install sodium' {{oxy_base_dir}}/oxy_manager.bash | cat
  register: grep

- name: run sodium_fixer
  shell: sh {{oxy_base_dir}}/sodium_fixer.sh
  when: grep.stdout == ""

- name: Check if oxy_manager can start
  shell: '{{oxy_base_dir}}/oxy_manager.bash start | grep -i error'
  register: oxystart
  ignore_errors: yes

- name: install oxy_manager
  become: yes
  shell: '{{oxy_base_dir}}/oxy_manager.bash install'
  when: oxystart.stdout != "" or oxystart.stderr != ""

- name: Make sure Oxy is stopped again
  shell: '{{oxy_base_dir}}/oxy_manager.bash stop'

- name: install oxy_manager wallet
  become: yes
  shell: '{{oxy_base_dir}}/oxy_manager.bash install_wallet'
  when: false

- name: Set oxy user as owner of oxy-onde folder
  shell: 'chown -R oxy:oxy {{oxy_base_dir}}'
  become: yes

- name: reload oxy
  shell: '{{oxy_base_dir}}/oxy_manager.bash reload'
